import Head from "next/head";
import { Header } from "src/components/Header";
import { Main } from "src/components/Main";

export default function About() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main title="about" />
    </>
  );
}
